@echo off
echo Starting Backend...
start "Backend" python backend\backend_core.py
echo Starting Worker...
start "Worker" python backend\redis_worker.py
echo Waiting 5 seconds for services to start...
timeout /t 5 /nobreak
echo Starting Mock Signal Generator for 15 seconds...
start "MockSignalGenerator" python backend\mock_signal_generator.py
echo Waiting 15 seconds for mock data...
timeout /t 15 /nobreak
echo Stopping Mock Signal Generator...
for /f "tokens=2" %%i in ('wmic process where "commandline like '%%mock_signal_generator.py%%'" get processid ^| findstr [0-9]') do taskkill /f /pid %%i
echo Test completed. Backend and Worker are still running.
echo You can now view the dashboard at http://localhost:5173
pause