#!/bin/bash
# Automated Changelog Generator for P31 Monorepo
# Generates changelogs from conventional commits

set -e

echo "📝 P31 Changelog Generator"
echo "=========================="

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

# Default values
SINCE_TAG=""
OUTPUT_FILE="CHANGELOG.md"
DRY_RUN=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --since=*)
            SINCE_TAG="${1#*=}"
            shift
            ;;
        --output=*)
            OUTPUT_FILE="${1#*=}"
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --help)
            echo "Usage: $0 [--since=tag] [--output=file] [--dry-run]"
            echo ""
            echo "Options:"
            echo "  --since=tag    Generate changelog since this git tag"
            echo "  --output=file  Output file (default: CHANGELOG.md)"
            echo "  --dry-run      Show what would be generated without writing"
            echo ""
            echo "Examples:"
            echo "  $0 --since=v1.0.0"
            echo "  $0 --output=CHANGELOG-v2.md --dry-run"
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            echo "Use --help for usage"
            exit 1
            ;;
    esac
done

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo -e "${RED}Error: Not in a git repository${NC}"
    exit 1
fi

# Determine the range
if [ -n "$SINCE_TAG" ]; then
    if ! git tag | grep -q "^${SINCE_TAG}$"; then
        echo -e "${RED}Error: Tag '$SINCE_TAG' not found${NC}"
        exit 1
    fi
    RANGE="${SINCE_TAG}..HEAD"
    HEADER="Changes since ${SINCE_TAG}"
else
    # Generate since last tag or all history
    LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
    if [ -n "$LAST_TAG" ]; then
        RANGE="${LAST_TAG}..HEAD"
        HEADER="Changes since ${LAST_TAG}"
    else
        RANGE="--all"
        HEADER="All Changes"
    fi
fi

echo "Generating changelog:"
echo "  Range: $RANGE"
echo "  Output: $OUTPUT_FILE"
echo "  Header: $HEADER"
echo "  Dry run: $DRY_RUN"
echo ""

# Generate the changelog content
generate_changelog() {
    local header="$1"
    local range="$2"

    cat << EOF
# $header

$(date +%Y-%m-%d)

This changelog was automatically generated from git commits.

## Changes

EOF

    # Process commits and categorize them
    declare -A categories=(
        ["feat"]="Features"
        ["fix"]="Bug Fixes"
        ["docs"]="Documentation"
        ["style"]="Styling"
        ["refactor"]="Code Refactoring"
        ["test"]="Tests"
        ["chore"]="Chores"
        ["perf"]="Performance Improvements"
        ["ci"]="CI/CD"
        ["build"]="Build System"
    )

    # Initialize category arrays
    declare -A category_commits
    for category in "${!categories[@]}"; do
        category_commits[$category]=""
    done

    # Parse commits
    while IFS= read -r commit_line; do
        # Extract commit info
        commit_hash=$(echo "$commit_line" | awk '{print $1}')
        commit_subject=$(echo "$commit_line" | sed 's/^[a-f0-9]* //')

        # Check for conventional commit format
        if [[ $commit_subject =~ ^([a-z]+)(\([a-z-]+\))?:\ (.+) ]]; then
            type="${BASH_REMATCH[1]}"
            scope="${BASH_REMATCH[2]}"
            description="${BASH_REMATCH[3]}"

            # Clean up scope
            scope=$(echo "$scope" | sed 's/[()]//g')

            # Format the commit line
            if [ -n "$scope" ]; then
                formatted="- **$description** ($scope) [$commit_hash]"
            else
                formatted="- **$description** [$commit_hash]"
            fi

            # Add to appropriate category
            if [[ -n "${categories[$type]}" ]]; then
                category_commits[$type]="${category_commits[$type]}$formatted\n"
            else
                category_commits["chore"]="${category_commits[chore]}$formatted\n"
            fi
        else
            # Non-conventional commit
            formatted="- $commit_subject [$commit_hash]"
            category_commits["chore"]="${category_commits[chore]}$formatted\n"
        fi
    done < <(git log --oneline --no-merges $range 2>/dev/null || echo "")

    # Output categorized changes
    for category in "${!categories[@]}"; do
        commits="${category_commits[$category]}"
        if [ -n "$commits" ]; then
            echo ""
            echo "### ${categories[$category]}"
            echo ""
            echo -e "$commits" | head -n -1  # Remove trailing newline
        fi
    done

    # Add footer
    cat << EOF

---

*Generated by P31 Changelog Generator*
*Conventional commits format: type(scope): description*
EOF
}

# Generate content
CONTENT=$(generate_changelog "$HEADER" "$RANGE")

# Output
if [ "$DRY_RUN" = true ]; then
    echo -e "${BLUE}=== DRY RUN - Generated Content ===${NC}"
    echo "$CONTENT"
    echo -e "${BLUE}=== END DRY RUN ===${NC}"
else
    echo "$CONTENT" > "$OUTPUT_FILE"
    echo -e "${GREEN}✓ Changelog generated: $OUTPUT_FILE${NC}"
    echo ""
    echo "Preview:"
    head -20 "$OUTPUT_FILE"
    echo "..."
fi

echo ""
echo -e "${GREEN}Changelog generation complete!${NC}"